name: flipnslide-dev

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - pystac
  - xarray
  - rioxarray
  - geopandas
  - ipykernel
  - jupyter-book
  - pip
  - pip:
    - flipnslide
    - torch
    - torchvision
    - tensorflow
    - planetary-computer
    - rasterio
    - GDAL
    - natsort
    - stackstac
