# In _config.yml
title: Flip-n-Slide
author: Ellianna Abrahams
# logo: logo.png
execute:
  execute_notebooks: 'off' #this saves time for read the docs limits

parse:
  myst_enable_extensions:  # See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution

# Add the code source repository
repository:
  url: https://github.com/elliesch/flipnslide
html:
  use_repository_button: true

# latex:
#   latex_engine              : pdflatex 
#   use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
#   latex_elements:
#     pxunit: "0.3cm"

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - ../paper/paper.bib

# Configure the citation style
sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.napoleon'    
  - 'sphinx.ext.viewcode'
  
  config:
    bibtex_reference_style: author_year
    add_module_names: False
    autosummary_generate: True
    autodoc_typehints: description         
    napoleon_google_docstring: False
    napoleon_numpy_docstring: True
    napoleon_include_init_with_doc: False
    napoleon_include_private_with_doc: False
    napoleon_include_special_with_doc: False
    napoleon_use_admonition_for_examples: False
    napoleon_use_admonition_for_notes: True
    napoleon_use_admonition_for_references: True
    napoleon_use_ivar: False
    napoleon_use_param: True
    napoleon_use_rtype: True
    suppress_warnings:
        - 'etoc.toctree'
        - 'etoc.tableofcontents'   
