# In _config.yml
title: Flip-n-Slide
author: Ellianna Abrahams
# logo: logo.png
execute:
  execute_notebooks: 'off' #this saves time for read the docs limits

# Add the code source repository
repository:
  url: https://github.com/elliesch/flipnslide
html:
  use_repository_button: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ../paper/paper.bib

# Configure the citation style
sphinx:
  config:
    bibtex_reference_style: author_year
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
